/**
 * Self-host the two webfonts: `npm run fonts`.
 *
 * WHY
 * ---
 * The pages used to pull Instrument Serif and Inter from fonts.googleapis.com.
 * That is one render-blocking stylesheet on a third-party origin, and it costs
 * more than it looks: a DNS lookup and a TLS handshake to fonts.googleapis.com,
 * then a *second* pair to fonts.gstatic.com for the files the stylesheet names,
 * all before a single word can be painted in the right face.
 *
 * There is a second reason, and for a portfolio read from Norway it is not a
 * small one: every visitor's IP address went to Google to fetch those fonts.
 * Self-hosting keeps that between the visitor and this site.
 *
 * Both families are licensed under the SIL Open Font License, which permits
 * exactly this.
 *
 * WHAT IT DOES
 * ------------
 * Downloads the woff2 files into fonts/, keeping only the `latin` and
 * `latin-ext` subsets — latin-ext is the one that carries ó, ł and ż for Polish
 * and ø, å, æ for Norwegian, so dropping it would quietly break half the names
 * on the site. Cyrillic, Greek and Vietnamese are not used and are skipped.
 *
 * Then it writes the @font-face rules straight into each page's <style> block,
 * between `fonts:start` and `fonts:end` markers, so there is no extra request
 * at all — not even a same-origin one.
 *
 * Uses curl rather than fetch() because this repo's sandbox reaches the network
 * through a proxy that Node's fetch does not honour; curl is also present on
 * macOS by default, so the script runs the same in both places.
 */

import { execFile } from 'node:child_process';
import { createHash } from 'node:crypto';
import { promisify } from 'node:util';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const run = promisify(execFile);
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'fonts');

const CSS_URL = 'https://fonts.googleapis.com/css2' +
  '?family=Instrument+Serif:ital@0;1&family=Inter:wght@400;500&display=swap';

/* Ask as a current browser or Google serves ttf instead of woff2. */
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
           '(KHTML, like Gecko) Chrome/120.0 Safari/537.36';

const KEEP = new Set(['latin', 'latin-ext']);

const PAGES = ['index.html', 'repapp.html', 'red-thread.html',
               'between-the-lines.html', 'hospital-wayfinding.html', '404.html'];

const START = '/* fonts:start — generated by tools/fonts.mjs, do not edit by hand */';
const END   = '/* fonts:end */';

const curl = async (url, binary = false) => {
  const args = ['-sSL', '--max-time', '60', '-A', UA, url];
  const { stdout } = await run('curl', binary ? [...args, '--output', '-'] : args,
    { encoding: binary ? 'buffer' : 'utf8', maxBuffer: 64 * 1024 * 1024 });
  return stdout;
};

/* ---------------------------------------------------------------- download */

await mkdir(OUT, { recursive: true });
const css = await curl(CSS_URL);

/* Each @font-face is preceded by a `/* subset *\/` comment naming its range. */
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]+\})/g)];
if (!blocks.length) throw new Error('could not parse the Google Fonts stylesheet');

const field = (block, name) =>
  block.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1].trim() ?? '';

const rules = [];
const byHash = new Map();          // content hash → filename already written
let bytes = 0, skipped = 0, shared = 0;

for (const [, subset, block] of blocks) {
  if (!KEEP.has(subset)) { skipped++; continue; }

  const family = field(block, 'font-family').replace(/['"]/g, '');
  const weight = field(block, 'font-weight');
  const style  = field(block, 'font-style');
  const range  = field(block, 'unicode-range');
  const url    = block.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
  if (!url) throw new Error(`no woff2 in the ${family} ${subset} block`);

  const data = await curl(url, true);
  const hash = createHash('sha256').update(data).digest('hex');

  /* Inter ships as a variable font, so Google hands back the *same* file for
     weight 400 and 500 — writing it once per weight would double the download
     for nothing. Key on the bytes and let both @font-face rules point at one
     file; the browser picks the weight off the variable axis. */
  let name = byHash.get(hash);
  if (name) {
    shared++;
    console.log(`  ${`${family} ${weight} ${style} ${subset}`.padEnd(46)} → shares ${name}`);
  } else {
    name = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}-${style}-${subset}.woff2`;
    await writeFile(join(OUT, name), data);
    byHash.set(hash, name);
    bytes += data.length;
    console.log(`  ${name.padEnd(46)} ${(data.length / 1024).toFixed(1)} KB`);
  }

  rules.push(
    `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};` +
    `font-display:swap;src:url(fonts/${name}) format('woff2');unicode-range:${range};}`);
}

console.log(`\n  ${rules.length} faces over ${byHash.size} files, ${(bytes / 1024).toFixed(0)} KB ` +
            `(${shared} faces share a file, ${skipped} unused subsets skipped)`);

/* ------------------------------------------------------------ inline them */

/* The case-study pages live one level up from nothing — every page sits in the
   repo root, so a plain relative `fonts/…` is correct for all of them. */
const payload = `${START}\n${rules.join('\n')}\n${END}`;

for (const page of PAGES) {
  const path = join(ROOT, page);
  let html = await readFile(path, 'utf8');

  if (html.includes(START)) {
    html = html.replace(
      new RegExp(`${START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`),
      payload);
  } else {
    const style = html.indexOf('<style>');
    if (style === -1) throw new Error(`${page}: no <style> block to inline into`);
    html = html.slice(0, style + '<style>'.length) + '\n' + payload +
           html.slice(style + '<style>'.length);
  }

  await writeFile(path, html, 'utf8');
  console.log(`  inlined into ${page}`);
}
